import {Router} from 'express';
import {body} from 'express-validator';
import {requireAuth,requireRoles} from '../middleware/auth.js';
import {validate} from '../middleware/validation.js';
import {asyncHandler} from '../utils/asyncHandler.js';
import * as c from '../controllers/productionController.js';
const r=Router(); r.use(requireAuth);
r.get('/',asyncHandler(c.list));
r.post('/',requireRoles('MASTER_ADMIN','ADMIN','STAFF'),[body('food').isMongoId(),body('producedQuantity').isFloat({gt:0}),body('unit').isIn(['portion','pcs','kg','l']),body('batchNo').isString().trim().notEmpty()],validate,asyncHandler(c.create));
export default r;
