export function printInvoice(invoice) {
  if (!invoice) return;
  const w = window.open('', '_blank', 'width=900,height=900');
  if (!w) return;
  const money = v => `₹${Number(v || 0).toFixed(2)}`;
  const rows = (invoice.items || []).map(i => `<tr><td>${escapeHtml(i.name)}</td><td>${i.quantity}</td><td>${money(i.unitPrice)}</td><td>${money(i.total)}</td></tr>`).join('');
  w.document.write(`<!doctype html><html><head><title>${escapeHtml(invoice.invoiceNo)}</title><style>body{font-family:Arial,sans-serif;margin:32px;color:#111}h1{margin:0}header{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:18px;margin-bottom:24px}.muted{color:#666}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}td:nth-child(2),td:nth-child(3),td:nth-child(4),th:nth-child(2),th:nth-child(3),th:nth-child(4){text-align:right}.totals{margin-left:auto;width:320px;margin-top:20px}.totals div{display:flex;justify-content:space-between;padding:6px}.grand{font-size:18px;font-weight:700;border-top:2px solid #111;margin-top:6px;padding-top:10px}@media print{button{display:none}}</style></head><body><header><div><h1>CANteen ERP</h1><div class="muted">Invoice</div></div><div><strong>${escapeHtml(invoice.invoiceNo)}</strong><div class="muted">${new Date(invoice.issuedAt || invoice.createdAt).toLocaleString()}</div></div></header><p><strong>Member:</strong> ${escapeHtml(invoice.member?.name || '—')}<br><strong>Order:</strong> ${escapeHtml(invoice.order?.orderNo || '—')}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Subtotal</span><strong>${money(invoice.subtotal)}</strong></div><div><span>Tax</span><strong>${money(invoice.tax)}</strong></div><div><span>Discount</span><strong>- ${money(invoice.discount)}</strong></div><div class="grand"><span>Grand Total</span><strong>${money(invoice.total)}</strong></div></div><p class="muted">Invoice status: ${escapeHtml(invoice.status || 'ISSUED')}</p><script>window.onload=()=>{window.print();}</script></body></html>`);
  w.document.close();
}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
