import { useEffect, useState } from 'react';
import api from '../services/api';

const empty = { name: '', description: '', image: '', status: 'ACTIVE' };

export default function CategoryManagement() {
  const [items,setItems]=useState([]), [form,setForm]=useState(empty), [editing,setEditing]=useState(null), [search,setSearch]=useState(''), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState('');
  async function load(){setLoading(true);try{const r=await api.get('/categories',{params:{q:search}});setItems(r.data.data.categories);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load categories')}finally{setLoading(false)}}
  useEffect(()=>{load();},[search]);
  function edit(x){setEditing(x._id);setForm({name:x.name,description:x.description||'',image:x.image||'',status:x.status});window.scrollTo({top:0,behavior:'smooth'})}
  function reset(){setEditing(null);setForm(empty)}
  async function submit(e){e.preventDefault();setSaving(true);try{if(editing)await api.put(`/categories/${editing}`,form);else await api.post('/categories',form);reset();await load()}catch(e){setError(e.response?.data?.message||'Unable to save category')}finally{setSaving(false)}}
  async function remove(id){if(!confirm('Delete this category?'))return;try{await api.delete(`/categories/${id}`);await load()}catch(e){setError(e.response?.data?.message||'Unable to delete category')}}
  return <div><div className="page-heading"><div><p className="eyebrow">Phase 2</p><h1>Category Management</h1><p className="muted">Organize the menu and see food counts.</p></div></div><div className="management-grid"><section className="panel form-panel"><h2>{editing?'Edit category':'Add category'}</h2><form onSubmit={submit}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label>Image URL<input value={form.image} onChange={e=>setForm({...form,image:e.target.value})} placeholder="https://..." /></label><label>Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-actions"><button className="primary" disabled={saving}>{saving?'Saving...':editing?'Update category':'Add category'}</button>{editing&&<button type="button" className="secondary" onClick={reset}>Cancel</button>}</div></form></section><section className="panel"><div className="toolbar"><input placeholder="Search category..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{error&&<div className="alert error">{error}</div>}{loading?<p className="muted">Loading...</p>:items.length===0?<div className="empty">No categories found.</div>:<div className="table-wrap"><table><thead><tr><th>Category</th><th>Food items</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x._id}><td><strong>{x.name}</strong><small>{x.description}</small></td><td>{x.foodCount}</td><td><span className={`pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td><button className="link-btn" onClick={()=>edit(x)}>Edit</button><button className="danger-btn" onClick={()=>remove(x._id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></div></div>
}
