import { useEffect, useState } from 'react';
import api from '../services/api';

export default function MemberManagement() {
  const [items,setItems]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState({name:'',mobile:'',role:'MEMBER',department:'',status:'ACTIVE'}),[search,setSearch]=useState(''),[role,setRole]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  async function load(){setLoading(true);try{const r=await api.get('/members',{params:{q:search,role:role||undefined}});setItems(r.data.data.members);setError('')}catch(e){setError(e.response?.data?.message||'Unable to load members')}finally{setLoading(false)}}
  useEffect(()=>{load()},[search,role]);
  function edit(x){setEditing(x._id);setForm({name:x.name||'',mobile:x.mobile||'',role:x.role,department:x.department||'',status:x.status});window.scrollTo({top:0,behavior:'smooth'})}
  function reset(){setEditing(null);setForm({name:'',mobile:'',role:'MEMBER',department:'',status:'ACTIVE'})}
  async function submit(e){e.preventDefault();setSaving(true);try{await api.put(`/members/${editing}`,form);reset();await load()}catch(e){setError(e.response?.data?.message||'Unable to update member')}finally{setSaving(false)}}
  async function remove(id){if(!confirm('Delete this member?'))return;try{await api.delete(`/members/${id}`);await load()}catch(e){setError(e.response?.data?.message||'Unable to delete member')}}
  return <div><div className="page-heading"><div><p className="eyebrow">Phase 2</p><h1>Member Management</h1><p className="muted">Manage members, staff roles and account status.</p></div></div>{editing&&<section className="panel form-panel compact-form"><h2>Edit member</h2><form onSubmit={submit}><div className="two-col"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></label><label>Mobile<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label></div><div className="two-col"><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['MEMBER','STAFF','ADMIN','MASTER_ADMIN'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></label></div><label>Department<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><div className="form-actions"><button className="primary" disabled={saving}>{saving?'Saving...':'Update member'}</button><button type="button" className="secondary" onClick={reset}>Cancel</button></div></form></section>}<section className="panel"><div className="toolbar"><input placeholder="Search name, email or mobile..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{['MEMBER','STAFF','ADMIN','MASTER_ADMIN'].map(x=><option key={x}>{x}</option>)}</select></div>{error&&<div className="alert error">{error}</div>}{loading?<p className="muted">Loading...</p>:items.length===0?<div className="empty">No members found.</div>:<div className="table-wrap"><table><thead><tr><th>Member</th><th>Mobile</th><th>Role</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x._id}><td><strong>{x.name}</strong><small>{x.email}</small></td><td>{x.mobile||'—'}</td><td>{x.role.replace('_',' ')}</td><td><span className={`pill ${x.status.toLowerCase()}`}>{x.status}</span></td><td>{new Date(x.createdAt).toLocaleDateString()}</td><td><button className="link-btn" onClick={()=>edit(x)}>Edit</button><button className="danger-btn" onClick={()=>remove(x._id)}>Delete</button></td></tr>)}</tbody></table></div>}</section></div>
}
